# Generated by Django 4.1.7 on 2023-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SclModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_name', models.CharField(default='', max_length=10)),
                ('Stud_result', models.BooleanField(default=False)),
                ('Stud_attend', models.IntegerField(default=0, max_length=10)),
                ('Stud_scl', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
