# Generated by Django 4.1.7 on 2023-02-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teach_name', models.CharField(default='', max_length=10)),
                ('Teach_room', models.IntegerField(default=0, max_length=10)),
                ('Teach_sub', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
