# Generated by Django 4.1.7 on 2023-02-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='', max_length=10)),
                ('Attendance', models.IntegerField(default='', max_length=10)),
                ('contact', models.IntegerField(default='', max_length=10)),
            ],
        ),
    ]
