# Generated by Django 4.1.7 on 2023-02-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teachername', models.CharField(default='', max_length=10)),
                ('Assigned_Sub', models.CharField(default='', max_length=10)),
                ('Staffroom_no', models.IntegerField(default=8, max_length=10)),
            ],
        ),
    ]
