# Generated by Django 4.1.7 on 2023-03-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song_title', models.CharField(default='', max_length=100)),
                ('Song_Favorite', models.BooleanField(default=False)),
                ('Singer_Name', models.CharField(default='', max_length=100)),
                ('Music_logo', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
