# Generated by Django 4.1.7 on 2023-03-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicclass',
            name='Music_logo',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
